<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.zbeboy</groupId>
    <artifactId>knife4j-simple</artifactId>
    <version>1.0-RELEASE</version>
    <packaging>pom</packaging>
    <name>io.github.zbeboy:knife4j-simple</name>
    <description>knife4j-simple</description>
    <url>https://github.com/zbeboy/knife4j-simple</url>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>zbeboy</name>
            <email>zbeboy@qq.com</email>
            <organization>zbeboysoftware</organization>
            <organizationUrl>zbeboysoftware.com</organizationUrl>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:git@github.com:zbeboy/knife4j-simple.git</connection>
        <developerConnection>scm:git:git@github.com:zbeboy/knife4j-simple.git</developerConnection>
        <url>git@github.com:zbeboy/knife4j-simple.git</url>
    </scm>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>knife4j-openapi3-spring-boot2-starter</module>
        <module>knife4j-openapi3-spring-boot3-starter</module>
        <module>knife4j-openapi3-spring-boot4-starter</module>
        <module>knife4j-openapi3-spring-boot2-demo</module>
        <module>knife4j-openapi3-spring-boot3-demo</module>
        <module>knife4j-openapi3-spring-boot4-demo</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                    <encoding>utf-8</encoding>
                    <compilerArguments>
                        <extdirs>${project.basedir}/lib</extdirs>
                    </compilerArguments>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>3.2.7</version>
                <configuration>
                    <gpgArguments>
                        <arg>--pinentry-mode</arg>
                        <arg>loopback</arg>
                    </gpgArguments>
                </configuration>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>0.7.0</version> <!-- 建议检查最新版本 -->
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>zbeboy-center</publishingServerId>
                    <autoPublish>false</autoPublish> <!-- 手动发布 -->
                    <waitUntil>uploaded</waitUntil> <!-- 等待上传完成 -->
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.2.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9.1</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>